version: "3"
services:
  jupyter:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      PYTHONPATH: /workspace
    volumes:
      - ..:/workspace
    ports:
      - 8090:8889
    networks:
      - composes_sd
    command: jupyter notebook --ip=0.0.0.0 --no-browser --allow-root

networks:
    composes_sd:
      external: true



