version: '3.7'
services:
  sistema_financeiro-sd:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      PYTHONPATH: /workspace
    volumes:
      - ..:/workspace
    ports:
      - 8091:8889
    networks:
      - sd
    command: jupyter notebook --ip=0.0.0.0 --no-browser --allow-root
    depends_on:
      postgres:
        condition: service_healthy
        restart: true

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - sd
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 50s
      timeout: 5s
      retries: 5

networks:
    sd:
      driver: bridge

